[project]
name = "digital-garden-chat"

[tool.pyside6-project]
files = ["config_manager.py", "conversation_manager.py", "knowledge_updater.py", "main.py", "main.qml", "markdown_formatter.py", "database_manager.py"]
